//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Externals_20MCA097.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment_Master
    {
        public int ap_id { get; set; }
        public string Patient_name { get; set; }
        public Nullable<System.DateTime> ap_date { get; set; }
        public string ap_for { get; set; }
    }
}
